export const ROUTER_PATHS = {
  ABOUT: '/about',
  CONFIRM_EMAIL: '/confirm-email',
  CONTACT: '/contact',
  EDIT_PROFILE: '/edit-profile',
  HOME: '/',
  LOGIN: '/login',
  PROFILE: '/profile',
  QUESTIONS: '/questions',
  REGISTER: '/register',
  SAVED: '/saved',
  TAGS: '/tags',
  USERS: '/users',
  ERROR_404: '/404',
} as const;
